// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物流方式枚举
type ShippingMethod int32

const (
	ShippingMethod_SHIPPING_METHOD_UNSPECIFIED ShippingMethod = 0
	ShippingMethod_SHIPPING_METHOD_STANDARD    ShippingMethod = 1
	ShippingMethod_SHIPPING_METHOD_EXPRESS     ShippingMethod = 2
	ShippingMethod_SHIPPING_METHOD_OVERNIGHT   ShippingMethod = 3
)

// Enum value maps for ShippingMethod.
var (
	ShippingMethod_name = map[int32]string{
		0: "SHIPPING_METHOD_UNSPECIFIED",
		1: "SHIPPING_METHOD_STANDARD",
		2: "SHIPPING_METHOD_EXPRESS",
		3: "SHIPPING_METHOD_OVERNIGHT",
	}
	ShippingMethod_value = map[string]int32{
		"SHIPPING_METHOD_UNSPECIFIED": 0,
		"SHIPPING_METHOD_STANDARD":    1,
		"SHIPPING_METHOD_EXPRESS":     2,
		"SHIPPING_METHOD_OVERNIGHT":   3,
	}
)

func (x ShippingMethod) Enum() *ShippingMethod {
	p := new(ShippingMethod)
	*p = x
	return p
}

func (x ShippingMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_shipping_proto_enumTypes[0].Descriptor()
}

func (ShippingMethod) Type() protoreflect.EnumType {
	return &file_shipping_shipping_proto_enumTypes[0]
}

func (x ShippingMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingMethod.Descriptor instead.
func (ShippingMethod) EnumDescriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

// 物流状态枚举
type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED      ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_CREATED          ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_LABEL_CREATED    ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_PICKED_UP        ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_IN_TRANSIT       ShipmentStatus = 4
	ShipmentStatus_SHIPMENT_STATUS_OUT_FOR_DELIVERY ShipmentStatus = 5
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED        ShipmentStatus = 6
	ShipmentStatus_SHIPMENT_STATUS_FAILED_DELIVERY  ShipmentStatus = 7
	ShipmentStatus_SHIPMENT_STATUS_RETURNED         ShipmentStatus = 8
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "SHIPMENT_STATUS_CREATED",
		2: "SHIPMENT_STATUS_LABEL_CREATED",
		3: "SHIPMENT_STATUS_PICKED_UP",
		4: "SHIPMENT_STATUS_IN_TRANSIT",
		5: "SHIPMENT_STATUS_OUT_FOR_DELIVERY",
		6: "SHIPMENT_STATUS_DELIVERED",
		7: "SHIPMENT_STATUS_FAILED_DELIVERY",
		8: "SHIPMENT_STATUS_RETURNED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED":      0,
		"SHIPMENT_STATUS_CREATED":          1,
		"SHIPMENT_STATUS_LABEL_CREATED":    2,
		"SHIPMENT_STATUS_PICKED_UP":        3,
		"SHIPMENT_STATUS_IN_TRANSIT":       4,
		"SHIPMENT_STATUS_OUT_FOR_DELIVERY": 5,
		"SHIPMENT_STATUS_DELIVERED":        6,
		"SHIPMENT_STATUS_FAILED_DELIVERY":  7,
		"SHIPMENT_STATUS_RETURNED":         8,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_shipping_proto_enumTypes[1].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_shipping_shipping_proto_enumTypes[1]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

// 创建物流订单请求
type CreateShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Origin         *Address               `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination    *Address               `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Packages       []*Package             `protobuf:"bytes,4,rep,name=packages,proto3" json:"packages,omitempty"`
	ShippingMethod ShippingMethod         `protobuf:"varint,5,opt,name=shipping_method,json=shippingMethod,proto3,enum=shipping.ShippingMethod" json:"shipping_method,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetOrigin() *Address {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CreateShipmentRequest) GetDestination() *Address {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *CreateShipmentRequest) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CreateShipmentRequest) GetShippingMethod() ShippingMethod {
	if x != nil {
		return x.ShippingMethod
	}
	return ShippingMethod_SHIPPING_METHOD_UNSPECIFIED
}

// 创建物流订单响应
type CreateShipmentResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId            string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status                ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipping.ShipmentStatus" json:"status,omitempty"`
	TrackingNumber        string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	EstimatedDeliveryDate string                 `protobuf:"bytes,4,opt,name=estimated_delivery_date,json=estimatedDeliveryDate,proto3" json:"estimated_delivery_date,omitempty"`
	ShippingCost          float64                `protobuf:"fixed64,5,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShipmentResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *CreateShipmentResponse) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *CreateShipmentResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateShipmentResponse) GetEstimatedDeliveryDate() string {
	if x != nil {
		return x.EstimatedDeliveryDate
	}
	return ""
}

func (x *CreateShipmentResponse) GetShippingCost() float64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

// 物流状态请求
type ShipmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentStatusRequest) Reset() {
	*x = ShipmentStatusRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentStatusRequest) ProtoMessage() {}

func (x *ShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*ShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShipmentStatusRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

// 物流状态响应
type ShipmentStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId      string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status          ShipmentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=shipping.ShipmentStatus" json:"status,omitempty"`
	CurrentLocation string                 `protobuf:"bytes,3,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	Events          []*ShipmentEvent       `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShipmentStatusResponse) Reset() {
	*x = ShipmentStatusResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentStatusResponse) ProtoMessage() {}

func (x *ShipmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentStatusResponse.ProtoReflect.Descriptor instead.
func (*ShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentStatusResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentStatusResponse) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ShipmentStatusResponse) GetCurrentLocation() string {
	if x != nil {
		return x.CurrentLocation
	}
	return ""
}

func (x *ShipmentStatusResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// 更新物流信息请求
type UpdateShipmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId      string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	NewStatus       ShipmentStatus         `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=shipping.ShipmentStatus" json:"new_status,omitempty"`
	CurrentLocation string                 `protobuf:"bytes,3,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	Notes           string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateShipmentRequest) Reset() {
	*x = UpdateShipmentRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentRequest) ProtoMessage() {}

func (x *UpdateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateShipmentRequest) GetNewStatus() ShipmentStatus {
	if x != nil {
		return x.NewStatus
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *UpdateShipmentRequest) GetCurrentLocation() string {
	if x != nil {
		return x.CurrentLocation
	}
	return ""
}

func (x *UpdateShipmentRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// 更新物流信息响应
type UpdateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentResponse) Reset() {
	*x = UpdateShipmentResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentResponse) ProtoMessage() {}

func (x *UpdateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateShipmentResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateShipmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 地址信息
type Address struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientName  string                 `protobuf:"bytes,1,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	StreetAddress1 string                 `protobuf:"bytes,2,opt,name=street_address1,json=streetAddress1,proto3" json:"street_address1,omitempty"`
	StreetAddress2 string                 `protobuf:"bytes,3,opt,name=street_address2,json=streetAddress2,proto3" json:"street_address2,omitempty"`
	City           string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode     string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country        string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	PhoneNumber    string                 `protobuf:"bytes,8,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_shipping_shipping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{6}
}

func (x *Address) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *Address) GetStreetAddress1() string {
	if x != nil {
		return x.StreetAddress1
	}
	return ""
}

func (x *Address) GetStreetAddress2() string {
	if x != nil {
		return x.StreetAddress2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

// 包裹信息
type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float64                `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	LengthCm      float64                `protobuf:"fixed64,2,opt,name=length_cm,json=lengthCm,proto3" json:"length_cm,omitempty"`
	WidthCm       float64                `protobuf:"fixed64,3,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	HeightCm      float64                `protobuf:"fixed64,4,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_shipping_shipping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{7}
}

func (x *Package) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *Package) GetLengthCm() float64 {
	if x != nil {
		return x.LengthCm
	}
	return 0
}

func (x *Package) GetWidthCm() float64 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *Package) GetHeightCm() float64 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 物流事件
type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=shipping.ShipmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_shipping_shipping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{8}
}

func (x *ShipmentEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ShipmentEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ShipmentEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShipmentEvent) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

var File_shipping_shipping_proto protoreflect.FileDescriptor

const file_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x17shipping/shipping.proto\x12\bshipping\"\x84\x02\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12)\n" +
	"\x06origin\x18\x02 \x01(\v2\x11.shipping.AddressR\x06origin\x123\n" +
	"\vdestination\x18\x03 \x01(\v2\x11.shipping.AddressR\vdestination\x12-\n" +
	"\bpackages\x18\x04 \x03(\v2\x11.shipping.PackageR\bpackages\x12A\n" +
	"\x0fshipping_method\x18\x05 \x01(\x0e2\x18.shipping.ShippingMethodR\x0eshippingMethod\"\xf1\x01\n" +
	"\x16CreateShipmentResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.shipping.ShipmentStatusR\x06status\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x126\n" +
	"\x17estimated_delivery_date\x18\x04 \x01(\tR\x15estimatedDeliveryDate\x12#\n" +
	"\rshipping_cost\x18\x05 \x01(\x01R\fshippingCost\"8\n" +
	"\x15ShipmentStatusRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"\xc7\x01\n" +
	"\x16ShipmentStatusResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.shipping.ShipmentStatusR\x06status\x12)\n" +
	"\x10current_location\x18\x03 \x01(\tR\x0fcurrentLocation\x12/\n" +
	"\x06events\x18\x04 \x03(\v2\x17.shipping.ShipmentEventR\x06events\"\xb2\x01\n" +
	"\x15UpdateShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x127\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x18.shipping.ShipmentStatusR\tnewStatus\x12)\n" +
	"\x10current_location\x18\x03 \x01(\tR\x0fcurrentLocation\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"m\n" +
	"\x16UpdateShipmentResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8a\x02\n" +
	"\aAddress\x12%\n" +
	"\x0erecipient_name\x18\x01 \x01(\tR\rrecipientName\x12'\n" +
	"\x0fstreet_address1\x18\x02 \x01(\tR\x0estreetAddress1\x12'\n" +
	"\x0fstreet_address2\x18\x03 \x01(\tR\x0estreetAddress2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12!\n" +
	"\fphone_number\x18\b \x01(\tR\vphoneNumber\"\x9d\x01\n" +
	"\aPackage\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x01R\bweightKg\x12\x1b\n" +
	"\tlength_cm\x18\x02 \x01(\x01R\blengthCm\x12\x19\n" +
	"\bwidth_cm\x18\x03 \x01(\x01R\awidthCm\x12\x1b\n" +
	"\theight_cm\x18\x04 \x01(\x01R\bheightCm\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x9d\x01\n" +
	"\rShipmentEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.shipping.ShipmentStatusR\x06status*\x8b\x01\n" +
	"\x0eShippingMethod\x12\x1f\n" +
	"\x1bSHIPPING_METHOD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SHIPPING_METHOD_STANDARD\x10\x01\x12\x1b\n" +
	"\x17SHIPPING_METHOD_EXPRESS\x10\x02\x12\x1d\n" +
	"\x19SHIPPING_METHOD_OVERNIGHT\x10\x03*\xb8\x02\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_CREATED\x10\x01\x12!\n" +
	"\x1dSHIPMENT_STATUS_LABEL_CREATED\x10\x02\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_PICKED_UP\x10\x03\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_IN_TRANSIT\x10\x04\x12$\n" +
	" SHIPMENT_STATUS_OUT_FOR_DELIVERY\x10\x05\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x06\x12#\n" +
	"\x1fSHIPMENT_STATUS_FAILED_DELIVERY\x10\a\x12\x1c\n" +
	"\x18SHIPMENT_STATUS_RETURNED\x10\b2\x99\x02\n" +
	"\x0fShippingService\x12U\n" +
	"\x0eCreateShipment\x12\x1f.shipping.CreateShipmentRequest\x1a .shipping.CreateShipmentResponse\"\x00\x12X\n" +
	"\x11GetShipmentStatus\x12\x1f.shipping.ShipmentStatusRequest\x1a .shipping.ShipmentStatusResponse\"\x00\x12U\n" +
	"\x0eUpdateShipment\x12\x1f.shipping.UpdateShipmentRequest\x1a .shipping.UpdateShipmentResponse\"\x00B8Z6github.com/redandblueqwer/microservices-proto/shippingb\x06proto3"

var (
	file_shipping_shipping_proto_rawDescOnce sync.Once
	file_shipping_shipping_proto_rawDescData []byte
)

func file_shipping_shipping_proto_rawDescGZIP() []byte {
	file_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)))
	})
	return file_shipping_shipping_proto_rawDescData
}

var file_shipping_shipping_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shipping_shipping_proto_goTypes = []any{
	(ShippingMethod)(0),            // 0: shipping.ShippingMethod
	(ShipmentStatus)(0),            // 1: shipping.ShipmentStatus
	(*CreateShipmentRequest)(nil),  // 2: shipping.CreateShipmentRequest
	(*CreateShipmentResponse)(nil), // 3: shipping.CreateShipmentResponse
	(*ShipmentStatusRequest)(nil),  // 4: shipping.ShipmentStatusRequest
	(*ShipmentStatusResponse)(nil), // 5: shipping.ShipmentStatusResponse
	(*UpdateShipmentRequest)(nil),  // 6: shipping.UpdateShipmentRequest
	(*UpdateShipmentResponse)(nil), // 7: shipping.UpdateShipmentResponse
	(*Address)(nil),                // 8: shipping.Address
	(*Package)(nil),                // 9: shipping.Package
	(*ShipmentEvent)(nil),          // 10: shipping.ShipmentEvent
}
var file_shipping_shipping_proto_depIdxs = []int32{
	8,  // 0: shipping.CreateShipmentRequest.origin:type_name -> shipping.Address
	8,  // 1: shipping.CreateShipmentRequest.destination:type_name -> shipping.Address
	9,  // 2: shipping.CreateShipmentRequest.packages:type_name -> shipping.Package
	0,  // 3: shipping.CreateShipmentRequest.shipping_method:type_name -> shipping.ShippingMethod
	1,  // 4: shipping.CreateShipmentResponse.status:type_name -> shipping.ShipmentStatus
	1,  // 5: shipping.ShipmentStatusResponse.status:type_name -> shipping.ShipmentStatus
	10, // 6: shipping.ShipmentStatusResponse.events:type_name -> shipping.ShipmentEvent
	1,  // 7: shipping.UpdateShipmentRequest.new_status:type_name -> shipping.ShipmentStatus
	1,  // 8: shipping.ShipmentEvent.status:type_name -> shipping.ShipmentStatus
	2,  // 9: shipping.ShippingService.CreateShipment:input_type -> shipping.CreateShipmentRequest
	4,  // 10: shipping.ShippingService.GetShipmentStatus:input_type -> shipping.ShipmentStatusRequest
	6,  // 11: shipping.ShippingService.UpdateShipment:input_type -> shipping.UpdateShipmentRequest
	3,  // 12: shipping.ShippingService.CreateShipment:output_type -> shipping.CreateShipmentResponse
	5,  // 13: shipping.ShippingService.GetShipmentStatus:output_type -> shipping.ShipmentStatusResponse
	7,  // 14: shipping.ShippingService.UpdateShipment:output_type -> shipping.UpdateShipmentResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shipping_shipping_proto_init() }
func file_shipping_shipping_proto_init() {
	if File_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_shipping_proto_depIdxs,
		EnumInfos:         file_shipping_shipping_proto_enumTypes,
		MessageInfos:      file_shipping_shipping_proto_msgTypes,
	}.Build()
	File_shipping_shipping_proto = out.File
	file_shipping_shipping_proto_goTypes = nil
	file_shipping_shipping_proto_depIdxs = nil
}
