name: Protocol Buffer Go Stubs Generation

on:
  push:
    tags:
      - v**          # 触发：打 v 前缀的 tag（如 v1.0.0）

jobs:
  protoc:
    name: Generate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order, payment, shipping]   # 按服务矩阵并行生成

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"                 # 如需新版可改为 '1.22'

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Generate for Golang
        shell: bash
        run: |
          # 针对每个 service 生成 Go 源码
          chmod +x run.sh
          run.sh "${{ matrix.service }}" "${{ env.RELEASE_VERSION }}"
          
